[package]
name = "melodic-music-mixing"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
loggit = "0.1.9"
once_cell = "1.21.3"
stratum-dsp = "1.0.0"
symphonia = "0.5.4"
thiserror = "2.0.12"
